development:
    dialect: postgres
    dir: migrations
    datasource: host=db user=postgres dbname=webapp sslmode=disable password=password
    table: migrations

production:
  dialect: postgres
  datasource: host=db user=postgres dbname=webapp sslmode=disable password=password
  dir: migrations
  table: migrations
